### ISSUE TITLE
space-after-touten(読点)

### ISSUE THREAD

**Issue by azu** [textlint-ja/textlint-rule-spacing#11]
> 句読点と英単語の間はスペース入れないルールがある
> https://twitter.com/_tyru_/status/756291298571587584

読点(、)の後にスペースをいれるかどうかのルール

## ルール

- 読点(、)の後にはスペースを入れる入れない
- ただし、箇条書き(名詞の列挙)は例外として扱う

## オプション

オプションは大きく分けて、本文と箇条書きの設定が必要そう

- "space":  "never"
- "space":  "always"
- "箇条書き":  "always"
- "箇条書き":  "never"

## 議論の余地

no-space-after-toutenなのか、space-after-toutenなのかがちょっと分からない。
no- なら常に` 、`の後にスペースを入れることがないのがデフォルトで、入れる場合はオプションで許可という形式。(逆に、スペースを入れる自動修正は行わない)
逆にspace-after-toutenなら"never" or "always"のオプションで決める。
( #8 と同じ方式)

オプション名のいい案がうかばない。
ESLintに似たようなのあるかなー?

- [Rule space-in-brackets - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/space-in-brackets "Rule space-in-brackets - ESLint - Pluggable JavaScript linter")

**Comment by gooocho** [comment]
読点(touten)?

**Comment by azu** [comment]
@gooocho Oops, 直しました。

**Comment by gooocho** [comment]
"とうてん"ですよー

**Comment by azu** [comment]
コピペミス…

**Comment by anyakichi** [comment]
私は全角半角間スペースは入れる派で、やはり句読点の後はなしでいいだろうと思って（この issue は知らずに）ソースコードを見てました。

ソースコード上は全角・半角間を検出するための全角文字の条件が
<pre>
[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF]|[\uD840-\uD87F][\uDC00-\uDFFF]|[ぁ-んァ-ヶ]
</pre>
となっていて、読点 (\u3001) はそもそも全角文字扱いされないのが正しいのかと思ったのですが、実際の動作としては全角文字扱いされて「スペースがない」と言われる状況でした。

ソースコードを見た感覚としては `[^ 　]` という条件が微妙に意図どおりの実装ではないような気がして、実際これを削除すると私の好みの挙動にはなりました。ちょっと言葉ではわかりづらいと思うので、変更も貼っておきます。

https://github.com/anyakichi/textlint-rule-spacing/commit/f2e521c413f59d6d0d3c76e986f1824250dcdb6c

`[^ 　]` を含む実装では実際は 3 文字間の関係性のチェックになっていて、
<pre>
あああ、bbb                                                                     
</pre>
だと検出されますが
<pre>
aaa、bbb
</pre>
だと検出されない、みたいな動作になってしまっています。

**Comment by azu** [comment]
ありがとうございます。ちょっと見てみます。

ja-space-between-half-and-full-width("always")

`aaa、bbb`  はエラーとならないことが期待される感じですかね？
(現状は "、" が全角として扱うため、`半角全角半角`となってエラーとなっている)

**Comment by anyakichi** [comment]
エラーになってしまうのは `あああ、bbb` の方ですが、おそらく今の正規表現の文字集合ではエラーにならないのが正しいかなと思います。

今の実装だと上記の入力が "always" -> "never" -> "always" で --fix したときに元に戻らないので。

**Comment by azu** [comment]
space-after-toutenとja-space-between-half-and-full-widthは
ja-space-between-half-and-full-widthにexceptPunctuation(、。)のオプションを追加すれば解決できるような気がするので、それで実装してみます。
